# version: '3.8'
services:
  # PHP82 (driver ODBC de Microsoft) + Node + Composer
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel-net

  # Nginx
  webserver:
    image: nginx:alpine
    container_name: laravel-nginx
    ports:
      - "8009:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel-net

  # MySQL
  db:
    image: mysql:8.4 # Versi√≥n LTS
    container_name: laravel-db
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: dev_password      
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel-net

  #Programador de tareas Laravel
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    command: ["sh", "-c", "while [ true ]; do php artisan schedule:run --verbose --no-interaction; sleep 60; done"]
    depends_on:
      - app

networks:
  laravel-net:
    driver: bridge

volumes:
  mysql_data: